## Pytorch Tensors

### Crear nuevos tensores

Pytorch maneja y guarda la información en los llamados **tensores** de Pytorch. Los tensores son una generalización de los vectoes y matrices a arrays multidimensionales. Operar con tensores de Pytorch es muy similar a operar con tensores de numpy. De esta forma, veremos que muchas operaciones o formas de trabajar se pueden realizar de la misma manera aquí.

In [4]:
import torch # Importamos el módulo de Pytorch
ones = torch.ones(5) # Creamos un vector de 5 componentes cuyo valor es '1'
ones

tensor([1., 1., 1., 1., 1.])

In [6]:
zeros = torch.zeros((5,5)) # Un vector/matriz de '0' puede ser una forma adecuada de inicialización
print("Matriz de ceros: \n", zeros)

# Construimos una matriz por columnas a partir de esta matriz de ceros
for i in range(len(zeros)):
    zeros[:,i] = i + 1

print("Nueva matriz: \n", zeros)

Matriz de ceros: 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
Nueva matriz: 
 tensor([[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.]])


También podemos crear un tensor de Pytorch a partir de una lista (o de un array de numpy):

In [7]:
lista = [1.0, 3.0, 5.0, 2.0, 9.0, 0.0]
lista = torch.tensor(lista)
lista

tensor([1., 3., 5., 2., 9., 0.])

In [8]:
lista = [[1.0, 3.0, 5.0], [2.0, 9.0, 0.0]] # Podemos añadirle dimensiones
lista = torch.tensor(lista)
lista

tensor([[1., 3., 5.],
        [2., 9., 0.]])

### Indexación de tensores

Podemos usar la misma indexación que en Numpy.

In [10]:
some_list = torch.tensor((list(range(6))))
some_list[:]     # <1>
some_list[1:4]   # <2>
some_list[1:]    # <3>
some_list[:4]    # <4>
some_list[:-1]   # <5>
some_list[1:4:2] # <6>

tensor([1, 3])

**<span style="color:red">añadir forma avanzada de tensor del capitulo 4</span>.**

### Broadcasting

Podemos operar con tensores aunque no tengan la misma dimensión **<span style="color:red">profundizar?</span>.**

In [23]:
matrix = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 6], [7, 8]])
matrix * matrix2 # producto elemento a elemento

tensor([[ 5, 12],
        [21, 32]])

In [24]:
torch.mm(matrix, matrix2) # producto matricial

tensor([[19, 22],
        [43, 50]])

In [33]:
vector = torch.tensor([1, 2]) # producto elemento a elemento en una dimension
vector = vector.unsqueeze(-1)
matrix * vector

tensor([[1, 2],
        [6, 8]])

In [34]:
matrix.shape, vector.shape

(torch.Size([2, 2]), torch.Size([2, 1]))

In [36]:
matrix * vector.view(1, 2) # Usamos view para hacer un 'reshape'

tensor([[1, 4],
        [3, 8]])

### Tipos de elementos

En Pytorch tenemos distintos tipos de elementos para representar: enteros, punto flotantes, etc.
En el caso de las redes neuronales, se suele usar **float32**, tiene menos precisión que 64-bit pero ganamos en memoria sin un fuerte impacto en la precisión del modelo. Pytorch espera que el indexado se haga con tensores **int64**. Además para indicar si algo está o no presente (booleano) se utilizará el tipo **bool**.

- torch.float32 o torch.float
- torch.float64 o torch.double
- torch.float16 o torch.half
- torch.int8
- torch.uint8
- torch.int16 o torch.short
- torch.int32 o torch.int
- torch.int64 o torch.long
- torch.bool

In [60]:
vector1 = torch.tensor([1, 1, 1])
vector2 = torch.tensor([1.0, 1.0, 1.0])
vector1.dtype, vector2.dtype

(torch.int64, torch.float32)

In [61]:
vector1 = torch.tensor([1, 1, 1], dtype=torch.float64)
vector1

tensor([1., 1., 1.], dtype=torch.float64)

In [62]:
vector1 = torch.tensor([1, 1, 1], dtype=torch.bool)
vector1, vector1.dtype

(tensor([True, True, True]), torch.bool)

In [63]:
random_vector = torch.randn(3, 3).to(torch.double)
random_vector

tensor([[ 0.2313, -1.1728, -0.6453],
        [-1.3283, -0.4990,  0.7516],
        [-1.5333,  0.6149, -0.8768]], dtype=torch.float64)

### Copia de tensores

In [72]:
vector1 = torch.tensor([1, 2])
vector2 = vector1
vector2[0] = 0
vector1

tensor([0, 2])

In [73]:
vector1 = torch.tensor([1, 2])
vector2 = vector1.clone()
vector2[0] = 0
vector1

tensor([1, 2])

Vectores contiguos

### Tensor API

Vamos a ver las distintas operaciones que se pueden hacer con tensores. La gran mayoría está disponible en el módulo de torch por lo que pueden ser llamadas como métodos de un objeto tensor.

In [64]:
a = torch.ones(3, 4)
a_t = torch.transpose(a, 0, 1) # damos las dimensiones que queremos intercambiar
a.shape, a_t.shape

(torch.Size([3, 4]), torch.Size([4, 3]))

In [65]:
a = torch.ones(3, 4)
a_t = a.transpose(0,1) # usamos el método del vector (pueden usarse indistinguiblemente)
a.shape, a_t.shape

(torch.Size([3, 4]), torch.Size([4, 3]))

### Guardar los tensores en CPU y GPU

In [84]:
cpu_vector = torch.tensor([3, 4], device = 'cpu')
gpu_vector = torch.tensor([3, 4], device = 'cuda')
cpu_vector, gpu_vector

(tensor([3, 4]), tensor([3, 4], device='cuda:0'))

In [85]:
cpu_vector.to(device='cuda')

tensor([3, 4], device='cuda:0')

In [87]:
gpu_vector.cpu(), cpu_vector.cuda()

(tensor([3, 4]), tensor([3, 4], device='cuda:0'))

In [88]:
cpu_vector.to(device = 'cuda', dtype = torch.double)

tensor([3., 4.], device='cuda:0', dtype=torch.float64)

In [90]:
cpu_vector + gpu_vector

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [92]:
suma_gpu = cpu_vector.cuda() + gpu_vector
suma_gpu

tensor([6, 8], device='cuda:0')

In [93]:
suma_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [94]:
suma_gpu.cpu().numpy()

array([6, 8])

### Avanzado: Contiguos y dónde están

Los tensores contiguos son aquellos tensores que pueden ser recorridos sin dar saltos en memoria. Esto ayuda a la eficiencia de los algoritmos.

In [75]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)
a.is_contiguous(), a_t.is_contiguous()

(True, False)

Algunas funciones necesitan que el vector sea contiguo. Para ello podemos utilizar el método .contiguous()

In [78]:
a_t.view(3, 2)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [81]:
a_t.contiguous().view(3, 2).shape

torch.Size([3, 2])

### Ejercicios